from motion_server.failure.codes import FailureCode
from motion_server.failure.exceptions import (
    AuthorityBusyException,
    AuthorityException,
    AuthorityRequiredException,
    CommunicationException,
    CommunicationTimeoutException,
    ConfigurationException,
    DeviceAccessException,
    DeviceException,
    DeviceRejectedException,
    InvalidArgumentException,
    InvalidRequestException,
    InvalidStateException,
    LimitViolationException,
    MotionServerException,
    OperationBlockedException,
    OperationConflictException,
    OperationException,
    OperationTimeoutException,
    PermissionDeniedException,
    RequestException,
    ResourceNotFoundException,
    SdoObjectNotFoundException,
    ServerNotReadyException,
    StateException,
    UnknownCommandException,
    UnsupportedOperationException,
)
from motion_server.failure.mapping import (
    EXCEPTION_FAILURE_MAPPINGS,
    ExceptionFailureMapping,
    map_exception,
)
from motion_server.failure.models import Failure
from motion_server.failure.partial import ItemFailure, PartialFailure


__all__ = [
    "AuthorityBusyException",
    "AuthorityException",
    "AuthorityRequiredException",
    "CommunicationException",
    "CommunicationTimeoutException",
    "ConfigurationException",
    "DeviceAccessException",
    "DeviceException",
    "DeviceRejectedException",
    "EXCEPTION_FAILURE_MAPPINGS",
    "ExceptionFailureMapping",
    "Failure",
    "FailureCode",
    "InvalidArgumentException",
    "InvalidRequestException",
    "InvalidStateException",
    "ItemFailure",
    "LimitViolationException",
    "MotionServerException",
    "OperationBlockedException",
    "OperationConflictException",
    "OperationException",
    "OperationTimeoutException",
    "PartialFailure",
    "PermissionDeniedException",
    "RequestException",
    "ResourceNotFoundException",
    "SdoObjectNotFoundException",
    "ServerNotReadyException",
    "StateException",
    "UnknownCommandException",
    "UnsupportedOperationException",
    "map_exception",
]
