from enum import Enum


class FailureCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    AUTHORITY_BUSY = "AUTHORITY_BUSY"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    SERVER_NOT_READY = "SERVER_NOT_READY"
    INVALID_STATE = "INVALID_STATE"
    OPERATION_CONFLICT = "OPERATION_CONFLICT"
    OPERATION_BLOCKED = "OPERATION_BLOCKED"
    LIMIT_VIOLATION = "LIMIT_VIOLATION"

    TIMEOUT = "TIMEOUT"
    COMMUNICATION_FAILED = "COMMUNICATION_FAILED"
    DEVICE_ACCESS_FAILED = "DEVICE_ACCESS_FAILED"
    DEVICE_REJECTED = "DEVICE_REJECTED"

    PARTIAL_FAILURE = "PARTIAL_FAILURE"
    OPERATION_FAILED = "OPERATION_FAILED"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"
