from dataclasses import replace
import json
import timeit
from types import SimpleNamespace
import unittest
from unittest.mock import patch
import xml.etree.ElementTree as ET

from configuration.models import IoLinkPortConfig
from device.cpx_ap_i_ec.profile import CPXApIEcDeviceProfile
from device.io_link.iodd_catalog import iodd_device_info, parse_process_data_profiles
from device.io_link.process_data import decode_process_data
from motion_server.api.encoder import io_device_snapshot, io_link_input_channels
from motion_server.app.initialization import InitializationStatus
from motion_server.app.session import ServerRuntimeState, ServerSession
from motion_server.handlers.status.feedback import system_feedback_message
from motion_server.handlers.status.io_input_read import input_read
from motion_server.handlers.status.io_status import io_status_message
from tests.test_virtual_cpx_ap import exchange, virtual_cpx_master


# Independent IEEE754/network-order fixture, not generated by the decoder:
# 1.0, -2.0, 0.5, 0.0, 4.0, 5.0, ~26.8, then only bit23 set.
BALLUFF_RAW = bytes.fromhex(
    "3f800000 c0000000 3f000000 00000000 40800000 40a00000 41d66666 00800000"
)


def synthetic_profile(datatype, *, bits=16, refs="", definitions=""):
    root = ET.fromstring(f'''<IODevice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <DatatypeCollection>{definitions}</DatatypeCollection>
        <ProcessData id="test"><ProcessDataIn id="input" bitLength="{bits}">
        {datatype}<Name textId="input_name"/></ProcessDataIn></ProcessData>
        <UserInterface>{refs}</UserInterface>
        <PrimaryLanguage><Text id="input_name" value="Test Input"/></PrimaryLanguage>
        </IODevice>''')
    return parse_process_data_profiles(root)[0]


def cpx_profile():
    return CPXApIEcDeviceProfile(device_config=SimpleNamespace(
        logical_id="io0",
        modules=(SimpleNamespace(slot=1, module_type="iol:4:in128:out128"),),
        io_link_ports=(
            IoLinkPortConfig("0", "balluffbcmr16e004ci01"),
            IoLinkPortConfig("1", "balluffbcmr16e004ci01", 2),
        ),
    ))


def device_entry(slave, io_id="io0"):
    return {"id": io_id, "slave_index": 0, "profile": "cpx_ap_i_ec", "slave": slave}


class IoddDecoderTest(unittest.TestCase):
    def test_bundled_record_references_units_signed_floats_and_inactive_bits(self):
        profile = iodd_device_info("balluffbcmr16e004ci01").select_process_data_profile()
        status, decoded = decode_process_data(profile, BALLUFF_RAW)
        self.assertEqual(status, "ok")
        self.assertEqual(decoded["profile"], 1)
        self.assertEqual([v["value"] for v in decoded["values"][:6]], [1, -2, .5, 0, 4, 5])
        self.assertEqual(decoded["values"][0]["unit"], "mm/s")
        self.assertAlmostEqual(decoded["values"][6]["value"], 26.8, places=5)
        self.assertEqual(decoded["values"][6]["unit"], "°C")
        active = [v for v in decoded["status_bits"] if v["active"]]
        self.assertEqual(len(decoded["status_bits"]), 32)
        self.assertEqual([(v["subindex"], v["bit_offset"]) for v in active], [(16, 23)])
        self.assertIn("Severity Zone A", active[0]["name"])
        self.assertEqual(len(json.loads(json.dumps(decoded))["values"]), 7)

    def test_profile_selection_changes_metadata_not_shared_cached_object(self):
        device = iodd_device_info("balluffbcmr16e004ci01")
        first = device.select_process_data_profile()
        second = device.select_process_data_profile(2)
        self.assertEqual(decode_process_data(second, BALLUFF_RAW)[1]["values"][0]["unit"], "g")
        self.assertEqual(decode_process_data(first, BALLUFF_RAW)[1]["values"][0]["unit"], "mm/s")
        self.assertEqual(decode_process_data(second, BALLUFF_RAW)[1]["profile"], 2)

    def test_signed_unsigned_widths_and_boolean_scalar(self):
        for kind, bits, raw, expected in [
            ("IntegerT", 16, "fffe", -2), ("UIntegerT", 16, "fffe", 65534),
            ("IntegerT", 12, "0fff", -1), ("UIntegerT", 64, "ffffffffffffffff", 2**64-1),
        ]:
            with self.subTest(kind=kind, bits=bits):
                profile = synthetic_profile(f'<Datatype xsi:type="{kind}" bitLength="{bits}"/>', bits=bits)
                status, decoded = decode_process_data(profile, bytes.fromhex(raw))
                self.assertEqual(status, "ok")
                self.assertEqual(decoded["values"][0]["value"], expected)
                self.assertIsNone(decoded["profile"])
                self.assertEqual(decoded["values"][0]["subindex"], 0)
        profile = synthetic_profile('<Datatype xsi:type="BooleanT"/>', bits=1)
        self.assertFalse(decode_process_data(profile, b"\x00")[1]["status_bits"][0]["active"])
        self.assertTrue(decode_process_data(profile, b"\x01")[1]["status_bits"][0]["active"])

    def test_non_aligned_record_bits_and_scale(self):
        profile = synthetic_profile('''<Datatype xsi:type="RecordT" bitLength="16">
          <RecordItem subindex="1" bitOffset="3"><SimpleDatatype xsi:type="IntegerT" bitLength="12"/></RecordItem>
          <RecordItem subindex="2" bitOffset="0"><SimpleDatatype xsi:type="BooleanT"/></RecordItem>
        </Datatype>''', refs='''<ProcessDataRef processDataId="input">
          <ProcessDataRecordItemInfo subindex="1" gradient="0.5" offset="10" unitCode="999999"/>
        </ProcessDataRef>''')
        status, decoded = decode_process_data(profile, bytes.fromhex("7ff1"))
        self.assertEqual(status, "ok")
        self.assertEqual(decoded["values"][0]["value"], 9)
        self.assertIsNone(decoded["values"][0]["unit"])
        self.assertTrue(decoded["status_bits"][0]["active"])

    def test_scalar_conversion_and_profile_padding(self):
        profile = synthetic_profile('<Datatype xsi:type="UIntegerT" bitLength="16"/>', refs='''
        <ProcessDataRef processDataId="input"><ProcessDataInfo gradient="0.1" offset="-2" unitCode="1001"/></ProcessDataRef>''')
        status, decoded = decode_process_data(profile, bytes.fromhex("0064deadbeef"))
        self.assertEqual(status, "ok")
        self.assertEqual(decoded["values"][0]["value"], 8)
        self.assertEqual(decoded["values"][0]["unit"], "°C")

    def test_unsupported_types_and_unresolved_references(self):
        for declaration in [
            '<Datatype xsi:type="ArrayT" count="2"/>',
            '<Datatype xsi:type="StringT" fixedLength="2" encoding="UTF-8"/>',
            '<Datatype xsi:type="OctetStringT" fixedLength="2"/>',
            '<Datatype xsi:type="VendorSpecificT"/>',
            '<DatatypeRef datatypeId="missing"/>',
            '<Datatype xsi:type="IntegerT" bitLength="0"/>',
            '<Datatype xsi:type="UIntegerT" bitLength="1000000000"/>',
            '<Datatype xsi:type="Float32T"/>',  # 16-bit input cannot hold Float32
            '',
        ]:
            with self.subTest(declaration=declaration):
                profile = synthetic_profile(declaration)
                self.assertEqual(decode_process_data(profile, b"\0\0"), ("unsupported", None))

    def test_malformed_and_nested_records_are_unsupported(self):
        for items in [
            '<RecordItem subindex="1" bitOffset="0"><Datatype xsi:type="RecordT" bitLength="16"/></RecordItem>',
            '<RecordItem subindex="1" bitOffset="15"><Datatype xsi:type="UIntegerT" bitLength="16"/></RecordItem>',
            '<RecordItem subindex="1" bitOffset="-1"><Datatype xsi:type="BooleanT"/></RecordItem>',
            '<RecordItem subindex="1" bitOffset="0"><Datatype xsi:type="BooleanT"/></RecordItem>' * 2,
            '',
        ]:
            profile = synthetic_profile(f'<Datatype xsi:type="RecordT" bitLength="16">{items}</Datatype>')
            self.assertEqual(decode_process_data(profile, b"\0\0"), ("unsupported", None))

    def test_bad_conversion_and_ambiguous_refs_are_unsupported(self):
        declaration = '<Datatype xsi:type="UIntegerT" bitLength="16"/>'
        for refs in [
            '<ProcessDataRef processDataId="input"><ProcessDataInfo gradient="NaN"/></ProcessDataRef>',
            '<ProcessDataRef processDataId="input"><ProcessDataInfo offset="inf"/></ProcessDataRef>',
            '<ProcessDataRef processDataId="input"><ProcessDataInfo/><ProcessDataInfo/></ProcessDataRef>',
            '<ProcessDataRef processDataId="input"/>' * 2,
            '<ProcessDataRef processDataId="input"><ProcessDataRecordItemInfo subindex="1"/></ProcessDataRef>',
        ]:
            self.assertEqual(decode_process_data(synthetic_profile(declaration, refs=refs), b"\0\0"), ("unsupported", None))

    def test_bad_lengths_nonfinite_and_data_validity(self):
        profile = synthetic_profile('<Datatype xsi:type="Float32T"/>', bits=32)
        for raw in [b"", b"\0" * 3, bytes.fromhex("7fc00000"), bytes.fromhex("7f800000"), bytes.fromhex("ff800000")]:
            self.assertEqual(decode_process_data(profile, raw), ("invalid_data", None))
        self.assertEqual(decode_process_data(profile, b"\0" * 4, data_valid=False), ("invalid_data", None))
        self.assertEqual(decode_process_data(None, b""), ("not_configured", None))


class IoLinkSnapshotTest(unittest.TestCase):
    def setUp(self):
        self.profile = cpx_profile()
        self.module = self.profile.config.layout.modules[0]
        self.payload = BALLUFF_RAW * 4 + bytes([0xA0, 0xE0, 0, 0])

    def channels(self, payload=None, valid=True, config=None):
        return io_link_input_channels(
            self.payload if payload is None else payload, self.module,
            self.profile.config if config is None else config, process_data_valid=valid,
        )

    def test_qualifier_and_not_configured_contract(self):
        channels = self.channels()
        self.assertEqual([p["decode_status"] for p in channels], ["ok", "ok", "not_configured", "not_configured"])
        self.assertEqual(channels[0]["qualifier"], 0xA0)
        self.assertEqual(channels[1]["qualifier"], 0xE0)  # DevErr is not data invalidity
        for qualifier in [0, 0x20, 0x80, 0x40]:
            payload = self.payload[:128] + bytes([qualifier, 0xA0, 0, 0])
            result = self.channels(payload)
            self.assertEqual(result[0]["decode_status"], "invalid_data")
            self.assertIsNone(result[0]["decoded"])
            self.assertEqual(result[0]["data"], BALLUFF_RAW.hex())
            self.assertEqual(result[1]["decode_status"], "ok")

    def test_missing_qualifier_and_bus_invalid_do_not_publish_stale_measurements(self):
        self.assertIsNone(self.channels(self.payload[:128])[0]["qualifier"])
        self.assertEqual(self.channels(self.payload[:128])[0]["decode_status"], "invalid_data")
        self.assertEqual(self.channels(valid=False)[0]["decode_status"], "invalid_data")

    def test_port_failure_does_not_affect_other_ports_or_module_bindings(self):
        broken = synthetic_profile('<Datatype xsi:type="ArrayT"/>')
        bindings = self.profile.config.io_link_devices
        config = replace(self.profile.config, io_link_devices=(replace(bindings[0], process_data_profile=broken), bindings[1]))
        channels = self.channels(config=config)
        self.assertEqual(channels[0]["decode_status"], "unsupported")
        self.assertEqual(channels[1]["decode_status"], "ok")
        foreign = replace(self.profile.config, io_link_devices=(replace(bindings[0], module=2),))
        self.assertEqual(self.channels(config=foreign)[0]["decode_status"], "not_configured")
        self.assertEqual(self.channels()[0]["decode_status"], "ok")

    def test_variant_padding_preserved_but_excluded_from_decode(self):
        short = synthetic_profile('<Datatype xsi:type="UIntegerT" bitLength="16"/>')
        binding = replace(self.profile.config.io_link_devices[0], process_data_profile=short)
        config = replace(self.profile.config, io_link_devices=(binding,))
        channel = self.channels(config=config)[0]
        self.assertEqual(channel["data"], BALLUFF_RAW.hex())
        self.assertEqual(channel["decoded"]["values"][0]["value"], 0x3f80)

    def test_real_codec_and_mock_raw_injection_parity_without_runtime_xml_or_sdo(self):
        master, virtual = virtual_cpx_master(self.profile)
        try:
            master.connect(target_state="preop")
            virtual.set_io_link_input(1, self.payload)
            exchange(master)
            real_slave = SimpleNamespace(rxpdo=self.profile.create_rxpdo(), txpdo=self.profile.create_txpdo())
            self.profile.pdo_codec.decode_txpdo(
                self.payload.ljust(real_slave.txpdo.mapping_size(), b"\0"), real_slave.txpdo,
            )
            with patch("xml.etree.ElementTree.parse", side_effect=AssertionError("runtime XML")):
                mock = io_device_snapshot(device_entry(master.slaves[0]))
                real = io_device_snapshot(device_entry(real_slave))
            self.assertEqual(mock, real)
            inputs = mock["modules"][0]["inputs"]
            self.assertNotIn("io_link_qualifiers", inputs)
            self.assertEqual(inputs["io_link_channels"][0]["decode_status"], "ok")
            self.assertEqual(set(mock["modules"][0]["outputs"]["io_link_channels"][0]), {"port", "data"})
        finally:
            master.close()

    def test_feedback_status_and_read_share_schema_and_bus_validity(self):
        slave = SimpleNamespace(rxpdo=self.profile.create_rxpdo(), txpdo=self.profile.create_txpdo())
        self.profile.pdo_codec.decode_txpdo(self.payload.ljust(slave.txpdo.mapping_size(), b"\0"), slave.txpdo)
        device = device_entry(slave)
        other = device_entry(SimpleNamespace(rxpdo=self.profile.create_rxpdo(), txpdo=self.profile.create_txpdo()), "io1")
        io = SimpleNamespace(devices=[device, other], selected_device=lambda *args: device)
        runtime = SimpleNamespace(slaves=[], device_manager=SimpleNamespace(io=io))
        session = ServerSession(InitializationStatus.ready(), runtime=runtime)
        state = {"server_session": session}
        for runtime_state, expected in [(ServerRuntimeState.NORMAL, "ok"), (ServerRuntimeState.BUS_DISCONNECTED, "invalid_data")]:
            session.set_runtime_state(runtime_state)
            feedback = system_feedback_message(runtime, state)["io"]["devices"]
            status = io_status_message(runtime, state)["devices"]
            read = input_read({"io": "io0"}, runtime, state, None)
            self.assertEqual(feedback, status)
            self.assertEqual(feedback[0], read)
            channel = read["modules"][0]["inputs"]["io_link_channels"][0]
            self.assertEqual(channel["decode_status"], expected)
            self.assertEqual(feedback[1]["modules"][0]["inputs"]["io_link_channels"][0]["decode_status"], "invalid_data")

    def test_four_port_payload_and_decode_cost_budget(self):
        binding = self.profile.config.io_link_devices[0]
        self.profile.config = replace(self.profile.config, io_link_devices=tuple(
            replace(binding, port=port) for port in range(4)
        ))
        slave = SimpleNamespace(rxpdo=self.profile.create_rxpdo(), txpdo=self.profile.create_txpdo())
        payload = BALLUFF_RAW * 4 + bytes([0xA0] * 4)
        self.profile.pdo_codec.decode_txpdo(payload.ljust(slave.txpdo.mapping_size(), b"\0"), slave.txpdo)
        device = device_entry(slave)

        def serialize():
            return json.dumps(io_device_snapshot(device), ensure_ascii=False)

        self.assertLess(len(serialize().encode("utf-8")), 32 * 1024)
        # Generous smoke regression budget, not a real-time scheduling guarantee.
        self.assertLess(min(timeit.repeat(serialize, number=100, repeat=3)) / 100, 0.005)


if __name__ == "__main__":
    unittest.main()
