#!/usr/bin/env bash

prepare_compose_env_file() {
  local project_root="$1"
  local base_env="${project_root}/.env"
  local runtime_dir="${project_root}/.runtime"
  local combined_env="${runtime_dir}/compose.env"

  if [[ ! -f "${base_env}" ]]; then
    echo "Missing ${base_env}" >&2
    echo "Create it from .env.example first." >&2
    echo "  cp .env.example .env" >&2
    return 1
  fi

  mkdir -p "${runtime_dir}"
  {
    echo "# Generated by scripts/env.sh. Do not edit."
    echo "# Base env: ${base_env}"
    cat "${base_env}"
    local device_env_file
    device_env_file="$(
      set -a
      # shellcheck disable=SC1090
      source "${base_env}"
      printf '%s' "${PYSOEM_DEVICE_ENV_FILE:-}"
    )"
    if [[ -z "${device_env_file}" ]]; then
      local bus
      bus="$(
        set -a
        # shellcheck disable=SC1090
        source "${base_env}"
        printf '%s' "${PYSOEM_BUS:-cmmt}"
      )"
      if [[ ",${bus}," == *",cmmt,"* || ",${bus}," == *":cmmt,"* ]]; then
        device_env_file="device/cmmt/.env"
      fi
    fi

    if [[ -n "${device_env_file}" ]]; then
      if [[ "${device_env_file}" != /* ]]; then
        device_env_file="${project_root}/${device_env_file}"
      fi
      if [[ -f "${device_env_file}" ]]; then
        echo ""
        echo "# Device env: ${device_env_file}"
        cat "${device_env_file}"
      else
        echo "Warning: device env file not found: ${device_env_file}" >&2
      fi
    fi

    local backend
    backend="$(
      set -a
      # shellcheck disable=SC1090
      source "${base_env}"
      printf '%s' "${MOTION_SERVER_BACKEND:-${AXIS_SERVER_BACKEND:-}}"
    )"
    if [[ "${backend}" == "mock" ]]; then
      local virtual_env_file
      virtual_env_file="$(
        set -a
        # shellcheck disable=SC1090
        source "${base_env}"
        printf '%s' "${VIRTUAL_SERVO_DRIVE_ENV_FILE:-device/virtual_servo_drive/.env}"
      )"
      if [[ "${virtual_env_file}" != /* ]]; then
        virtual_env_file="${project_root}/${virtual_env_file}"
      fi
      if [[ -f "${virtual_env_file}" ]]; then
        echo ""
        echo "# Virtual servo drive env: ${virtual_env_file}"
        cat "${virtual_env_file}"
      else
        echo "Warning: virtual servo drive env file not found: ${virtual_env_file}" >&2
      fi
    fi
  } > "${combined_env}"

  printf '%s\n' "${combined_env}"
}
