#!/usr/bin/env bash

append_env_file() {
  local env_file="$1"
  python3 - "${env_file}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
pending = ""
if not path.exists():
    raise SystemExit(0)

for raw_line in path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not pending and (not line or line.startswith("#")):
        continue
    continued = line.endswith("\\")
    if continued:
        line = line[:-1].strip()
    pending += line
    if continued:
        continue
    if pending:
        print(pending)
    pending = ""

if pending:
    print(pending)
PY
}

strip_index_label() {
  local item="$1"
  if [[ "${item}" =~ ^[0-9]+:(.*)$ ]]; then
    printf '%s' "${BASH_REMATCH[1]}"
  else
    printf '%s' "${item}"
  fi
}

env_value_from_file() {
  local env_file="$1"
  local name="$2"
  local default="$3"
  python3 - "${env_file}" "${name}" "${default}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
name = sys.argv[2]
default = sys.argv[3]
pending = ""
values = {}
if path.exists():
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not pending and (not line or line.startswith("#")):
            continue
        continued = line.endswith("\\")
        if continued:
            line = line[:-1].strip()
        pending += line
        if continued:
            continue
        if pending and "=" in pending:
            key, value = pending.split("=", 1)
            values[key.strip()] = value.strip().strip('"').strip("'")
        pending = ""
    if pending and "=" in pending:
        key, value = pending.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")

print(values.get(name, default))
PY
}

prepare_compose_env_file() {
  local project_root="$1"
  local base_env="${project_root}/.env"
  local runtime_dir="${project_root}/.runtime"
  local combined_env="${runtime_dir}/compose.env"

  if [[ ! -f "${base_env}" ]]; then
    echo "Missing ${base_env}" >&2
    echo "Create it from .env.example first." >&2
    echo "  cp .env.example .env" >&2
    return 1
  fi

  mkdir -p "${runtime_dir}"
  {
    echo "# Generated by scripts/env.sh. Do not edit."
    echo "# Base env: ${base_env}"
    append_env_file "${base_env}"
    local device_config_root
    device_config_root="$(env_value_from_file "${base_env}" "MOTION_SERVER_DEVICE_CONFIG_ROOT" "")"
    if [[ -z "${device_config_root}" ]]; then
      device_config_root="$(env_value_from_file "${base_env}" "PYSOEM_DEVICE_CONFIG_ROOT" "device")"
    fi
    if [[ "${device_config_root}" != /* ]]; then
      device_config_root="${project_root}/${device_config_root}"
    fi

    local bus
    bus="$(env_value_from_file "${base_env}" "MOTION_SERVER_BUS" "")"
    if [[ -z "${bus}" ]]; then
      bus="$(env_value_from_file "${base_env}" "PYSOEM_BUS" "cmmt")"
    fi
    local loaded_profiles=","
    local bus_entry profile device_env_file
    IFS=',' read -ra bus_entries <<< "${bus}"
    for bus_entry in "${bus_entries[@]}"; do
      bus_entry="${bus_entry//[[:space:]]/}"
      bus_entry="$(strip_index_label "${bus_entry}")"
      if [[ -z "${bus_entry}" ]]; then
        continue
      fi
      profile="${bus_entry}"
      if [[ "${bus_entry}" == *:* ]]; then
        IFS=':' read -r _role profile _logical_id <<< "${bus_entry}"
      fi
      if [[ "${loaded_profiles}" == *",${profile},"* ]]; then
        continue
      fi
      loaded_profiles="${loaded_profiles}${profile},"
      device_env_file="${device_config_root}/${profile}/.env"
      if [[ -f "${device_env_file}" ]]; then
        echo ""
        echo "# Device env: ${device_env_file}"
        append_env_file "${device_env_file}"
      else
        echo "Warning: device env file not found: ${device_env_file}" >&2
      fi
    done

    local backend
    backend="$(env_value_from_file "${base_env}" "MOTION_SERVER_BACKEND" "")"
    if [[ -z "${backend}" ]]; then
      backend="$(env_value_from_file "${base_env}" "AXIS_SERVER_BACKEND" "")"
    fi
    if [[ "${backend}" == "mock" ]]; then
      local virtual_env_file
      virtual_env_file="$(env_value_from_file "${base_env}" "VIRTUAL_SERVO_DRIVE_ENV_FILE" "device/virtual_servo_drive/.env")"
      if [[ "${virtual_env_file}" != /* ]]; then
        virtual_env_file="${project_root}/${virtual_env_file}"
      fi
      if [[ -f "${virtual_env_file}" ]]; then
        echo ""
        echo "# Virtual servo drive env: ${virtual_env_file}"
        append_env_file "${virtual_env_file}"
      else
        echo "Warning: virtual servo drive env file not found: ${virtual_env_file}" >&2
      fi
    fi
  } > "${combined_env}"

  printf '%s\n' "${combined_env}"
}
